#!/usr/bin/env bash
# scripts/index.sh — generated-mode Markdown index cache.
#
# Refreshes bounded Markdown indexes under <root>/.agent/indexes/ before an
# agent reads them, and reuses a verified prior build when nothing that
# feeds it has changed. Full documentation: scripts/docs/index.md.
#
# Usage:
#   index.sh ensure [--root <path>] [--budget <bytes>]
#   index.sh check  [--root <path>] [--budget <bytes>]
#   index.sh --help
#   index.sh --version
#
# ensure validates the existing entry against a fresh fingerprint of the
# canonical sources (<root>/.agent/rules/**/*.md and
# <root>/.agent/docs/**/*.md), reusing it on a match or rendering and
# publishing a new immutable generation otherwise. It prints one absolute
# path — <root>/.agent/indexes/current.md — to stdout on success. check
# performs the same validation without ever writing the cache and prints
# only FRESH or STALE to stdout. Both put HIT/BUILT/FRESH/STALE and every
# diagnostic on stderr; stdout never carries rule bodies or routing tables,
# only the bounded status documented above.
#
# Exit status: 0 success (ensure: HIT or BUILT; check: FRESH). 1 the
# answer is "not fresh" — ensure falls back to canonical sources named on
# stderr; check reports STALE. 2 a usage error: bad flags, a budget out of
# range, or a root with no <root>/.agent directory to index.
#
# bash 3.2 / BSD portable: no associative arrays, no GNU-only flags.
# No -E (errtrace): the ERR trap below is a top-level safety net for a
# command left unguarded in the main flow. Every helper function instead
# fails through its own explicit `|| return 1` / `|| fallback`, called
# only from if-conditions or the left of `||` — the contexts errexit
# already treats as "the caller decides". Without -E a subshell spawned
# while evaluating one of those (a command substitution, a `( ... )`
# pipeline stage) never re-fires this trap on its own account, so one
# real failure never prints more than one ERROR/FALLBACK pair.
set -euo pipefail
export LC_ALL=C

schema_version=1
usage() {
  cat <<'EOF'
Usage:
  index.sh ensure [--root <path>] [--budget <bytes>]
  index.sh check  [--root <path>] [--budget <bytes>]
  index.sh --help
  index.sh --version

root defaults to . — the cache lives at <root>/.agent/indexes/.
budget defaults to 30000 and bounds each generated page and the entry
file, in bytes (256..1000000).
EOF
}

self_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
self="$self_dir/${BASH_SOURCE[0]##*/}"

# Generations older than this, and not the newly published or immediately
# prior one, are reclaimed after a successful publish. Wide enough that no
# realistically concurrent build (seconds, per the benchmark) is ever a
# candidate; a crash-abandoned generation is reclaimed on the next publish
# that happens to run at least this long afterward.
CLEANUP_AGE_SECONDS=${INDEX_CLEANUP_AGE_SECONDS:-300}
MAX_BUILD_ATTEMPTS=5

case "${1:-}" in
--help | -h) usage; exit 0 ;;
--version) printf 'index.sh schema %s\n' "$schema_version"; exit 0 ;;
esac

op="${1:-}"
case "$op" in
ensure | check) shift ;;
*) usage >&2; exit 2 ;;
esac

root=$PWD
budget=30000
while [ "$#" -gt 0 ]; do
  case "$1" in
  --root | --budget)
    [ "$#" -ge 2 ] || { usage >&2; exit 2; }
    case "$1" in --root) root=$2 ;; --budget) budget=$2 ;; esac
    shift 2 ;;
  --help | -h) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
  esac
done
case "$budget" in '' | *[!0-9]*) usage >&2; exit 2 ;; esac
[ "$budget" -ge 256 ] && [ "$budget" -le 1000000 ] || { usage >&2; exit 2; }
[ -d "$root" ] || { usage >&2; exit 2; }
root=$(cd "$root" && pwd -P)
case "$root" in *\\* | *$'\n'* | *$'\r'* | *$'\t'*)
  printf 'index.sh: unsupported project path\n' >&2; exit 2 ;;
esac
[ -d "$root/.agent" ] || {
  printf 'index.sh: no %s/.agent directory — not a dot-agent node\n' "$root" >&2
  exit 2
}
cd "$root"
cache="$root/.agent/indexes"
entry="$cache/current.md"
learned_agg="$root/.agent/rules/learned.md"

# Carried verbatim from the header node.sh init writes at rules/learned.md,
# so status.sh's non-empty check and its rule/word counts hold even with
# zero rules/learned/ records.
learned_header=$(cat <<'HEADER_EOF'
# Learned rules

Binding rules distilled from operator corrections and failed verifications on this project, after the canonical-source check in `contract.md`. A correction that exposes a defect in the contract, docs, code, or tooling is fixed there and produces no compensating rule. Merging and compressing entries is allowed. Drop a rule when its failure mode becomes mechanically enforced. Behavioral rules stay here. Area gotchas go to the matching `.agent/docs/` file under `## Gotchas`. Authoring and curation rules: `contract.md`, Self-learning.

<!-- Format: - [YYYY-MM-DD] <imperative rule>. Trigger: <cause, optional>. -->
<!-- Generated by index.sh from rules/learned/*.md — hand edits here are lost on the next ensure. -->
HEADER_EOF
)

gen=''
entry_tmp=''
agg_tmp=''
keep=0
cleanup() {
  [ -z "$entry_tmp" ] || rm -f "$entry_tmp"
  [ -z "$agg_tmp" ] || rm -f "$agg_tmp"
  if [ -n "$gen" ] && [ "$keep" -eq 0 ]; then rm -rf "$gen"; fi
}
fallback() {
  printf 'ERROR: %s\n' "$*" >&2
  printf 'FALLBACK: read canonical Markdown under %s/.agent/rules/ and %s/.agent/docs/\n' "$root" "$root" >&2
  exit 1
}
trap cleanup EXIT
trap 'fallback "refresh failed at line $LINENO"' ERR
trap 'exit 130' INT
trap 'exit 143' TERM

[ ! -L "$cache" ] || fallback 'cache path is a symlink'
[ ! -d "$entry" ] || fallback 'entry path is a directory'

generator=$(git hash-object --no-filters -- "$self")

# True whenever <root>/.agent/rules/learned/ exists and holds at least one
# *.md record — the single switch that decides whether rules/learned.md is
# a canonical source (directory absent or empty: an ordinary rule record,
# untouched) or the generated aggregate paths() excludes below.
learned_dir_active() {
  lda_dir="$1/.agent/rules/learned"
  [ -d "$lda_dir" ] && [ ! -L "$lda_dir" ] || return 1
  [ -n "$(find "$lda_dir" -type f -name '*.md' -print -quit 2>/dev/null)" ]
}

# Byte-for-byte reproducible from the header above plus every
# rules/learned/*.md record's body, path-sorted, directly concatenated
# after one blank line — no separator between records, so a flat list of
# "- [date] rule" lines split one-per-file reaggregates into the same flat
# list byte-for-byte. A record missing its own trailing newline still gets
# one before the next record starts, so two records can never merge into
# a single line. No timestamps, hostnames, or counts, so an unrelated
# rebuild never churns this file when the record set itself hasn't changed.
learned_aggregate_content() {
  la_root="$1"
  printf '%s\n\n' "$learned_header"
  find "$la_root/.agent/rules/learned" -type f -name '*.md' | sort \
    | while IFS= read -r la_file; do
        cat "$la_file"
        [ "$(tail -c1 "$la_file" 2>/dev/null | wc -l | tr -d '[:space:]')" = 1 ] || printf '\n'
      done
}

# Restricted relative names make line-oriented batch hashing unambiguous
# and rule out path characters that would break the entry file's grammar.
# rules/learned.md is excluded from this same list — the one both the
# fingerprint and the render loop consume — whenever learned_dir_active,
# so the derived aggregate never feeds its own rebuild decision and its
# rule bodies never render a second time as an ordinary source record.
paths() {
  proot="$1"
  ( [ -d "$proot/.agent/rules" ] && find "$proot/.agent/rules" -type l -print
    [ -d "$proot/.agent/docs" ] && find "$proot/.agent/docs" -type l -print
    true ) 2>/dev/null \
    | awk 'END { if (NR) exit 1 }' || return 1
  p_learned_active=0
  if learned_dir_active "$proot"; then p_learned_active=1; fi
  ( [ -d "$proot/.agent/rules" ] && find "$proot/.agent/rules" -type f -name '*.md' -print0
    [ -d "$proot/.agent/docs" ] && find "$proot/.agent/docs" -type f -name '*.md' -print0
    true ) \
    | while IFS= read -r -d '' file; do
        rel=${file#"$proot"/}
        case "$rel" in *[!a-zA-Z0-9_./-]*) exit 1 ;; esac
        if [ "$p_learned_active" -eq 1 ] && [ "$rel" = .agent/rules/learned.md ]; then
          continue
        fi
        # rules/quality-bar.md and every references/ record are on-demand
        # by contract — opened only when a task needs them, never as part
        # of the always-read set — so rendering either one into a page
        # would load it every session, the cost each was split out to
        # avoid. Unconditional: neither tier is ever a rendered source.
        if [ "$rel" = .agent/rules/quality-bar.md ]; then
          continue
        fi
        case "$rel" in */references/*) continue ;; esac
        printf '%s\n' "$rel"
      done | sort
}

absolute_paths() {
  aproot="$1"
  while IFS= read -r file; do printf '%s/%s\n' "$aproot" "$file"; done
}

# Fingerprint binds generator bytes, render configuration (schema and
# budget), the project path, every canonical source's relative path, and
# its content bytes (via git hash-object, so an edit that preserves mtime
# still changes the hash). Git never writes an object for this — hashing
# is a pure content digest, not a repository write.
snapshot() {
  sn_list=$(paths "$root") || return 1
  [ -n "$sn_list" ] || return 1
  sn_hashes=$(printf '%s\n' "$sn_list" | absolute_paths "$root" | git hash-object --no-filters --stdin-paths) || return 1
  printf '%s\n%s\n%s\n%s\n' "$schema_version/$budget/$generator" "$root" "$sn_list" "$sn_hashes" | git hash-object --stdin
}

# The tree digest binds every published page's name to its content, so
# damage to one page, a missing page, or an extra stray file all change it.
tree_digest() {
  td_dir="$1"
  [ -d "$td_dir" ] && [ ! -L "$td_dir" ] || return 1
  td_list=$(cd "$td_dir" && find . -type f -name '*.md' | sed 's|^\./||' | sort) || return 1
  [ -n "$td_list" ] || return 1
  td_hashes=$(cd "$td_dir" && printf '%s\n' "$td_list" | absolute_paths "$td_dir" | git hash-object --no-filters --stdin-paths) || return 1
  printf '%s\n%s\n' "$td_list" "$td_hashes" | git hash-object --stdin
}

mtime_epoch() {
  if stat -f '%m' "$1" >/dev/null 2>&1; then
    stat -f '%m' "$1"
  else
    stat -c '%Y' "$1"
  fi
}

# Builds the exact byte content a valid, matching entry file must have for
# generation $1 (fingerprint/generation/tree header, then one direct READ
# line per page — no intermediate index file to open first). Used both to
# publish a new entry and to verify a candidate cache hit.
expected_entry() {
  ee_fp="$1" ee_gen="$2" ee_dir="$3"
  {
    printf '%s\n%s\n%s\n\n' "$ee_fp" "${ee_gen##*/}" "$(tree_digest "$ee_dir")"
    ( cd "$ee_dir" && find . -type f -name '*.md' | sed 's|^\./||' | sort ) \
      | while IFS= read -r pg; do printf 'READ: %s/%s\n' "$ee_dir" "$pg"; done
  }
}

# Sets HIT_ENTRY only on a fully verified hit: fingerprint match, a
# readable generation whose tree digest matches the recorded one, AND the
# entry's own bytes matching what that generation would produce today —
# catches direct tampering with current.md itself, not just its pages.
HIT_ENTRY=''
valid_hit() {
  vh_fp="$1"
  [ -f "$entry" ] && [ ! -L "$entry" ] || return 1
  vh_contents=$(cat "$entry") || return 1
  vh_old_fp=${vh_contents%%$'\n'*}; vh_rest=${vh_contents#*$'\n'}
  vh_old_gen=${vh_rest%%$'\n'*}
  case "$vh_old_gen" in
  gen.*) case "$vh_old_gen" in *[!a-zA-Z0-9.]* | *..*) return 1 ;; esac ;;
  *) return 1 ;;
  esac
  [ "$vh_old_fp" = "$vh_fp" ] || return 1
  vh_dir="$cache/$vh_old_gen"
  [ -d "$vh_dir" ] && [ ! -L "$vh_dir" ] || return 1
  vh_expected=$(expected_entry "$vh_fp" "$vh_old_gen" "$vh_dir") || return 1
  [ "$vh_contents" = "$vh_expected" ] || return 1
  HIT_ENTRY="$entry"
  return 0
}

# One awk process renders every record. .agent/rules/**/*.md become
# complete "rules" pages, each record's full body behind a "Source:"
# pointer — verbatim except that a relative Markdown link
# ([text](relative/path), not an absolute path, a #-only anchor, or a
# URL with a scheme) is rewritten to an absolute path so it still
# resolves once the body is copied into a generation directory elsewhere
# under .agent/indexes/ (see rewrite_links below). Everything else under
# .agent/docs/ becomes one "routes" line per file: its first "# "
# heading as title, the first "<!-- Read when: ... -->" comment's
# payload as hook (or "(no hook)"), and a direct READ pointer at the
# canonical source — the grammar this task defines and F15 adapts
# existing records to. Each page and the route index share one hard byte
# budget; a record too large to fit its own page, or an index line too
# large to fit the running index, fails rendering rather than truncating
# anything.
render() {
  rd_gen="$1"
  shift
  awk -v out="$rd_gen" -v canonical="$root" -v cap="$budget" '
    function emit(kind, text,    n,path) {
      n = length(text) + 1
      if (n > cap) { print "record exceeds page budget: " FILENAME_PREV > "/dev/stderr"; exit 4 }
      if (!page[kind] || size[kind] + n > cap) { page[kind]++; size[kind] = 0 }
      path = out "/" kind "-" page[kind] ".md"
      print text > path
      size[kind] += n
    }
    # A link target is relative when it has no URL scheme (http:,
    # mailto:, ...), is not rooted at "/", and is not a #-only anchor.
    function is_relative_link(url) {
      if (url == "") return 0
      if (url ~ /^[A-Za-z][A-Za-z0-9+.-]*:/) return 0
      if (url ~ /^\//) return 0
      if (url ~ /^#/) return 0
      return 1
    }
    # Collapses "." and ".." segments in a "/"-joined path (no leading
    # slash assumed or produced) the same way a filesystem would.
    function normalize_path(path,    n, parts, i, seg, outn, joined) {
      n = split(path, parts, "/")
      outn = 0
      for (i = 1; i <= n; i++) {
        seg = parts[i]
        if (seg == "" || seg == ".") continue
        if (seg == "..") { if (outn > 0) outn--; continue }
        outn++
        parts[outn] = seg
      }
      joined = ""
      for (i = 1; i <= outn; i++) joined = joined (i > 1 ? "/" : "") parts[i]
      return joined
    }
    # Rewrites every [text](relative/target) link in one line so the
    # target is an absolute path back to its original location under
    # dir (the source record own directory, project-relative).
    # Absolute paths, #-only anchors, and scheme URLs pass through
    # unchanged; a #fragment on a relative target is preserved.
    function rewrite_links(line, dir,    res, pos, s, mlen, full, sep, label, url, frag, base, resolved, fi, title, ti) {
      res = ""
      pos = 1
      while (match(substr(line, pos), /\[[^]]*\]\([^)]*\)/)) {
        s = pos + RSTART - 1
        mlen = RLENGTH
        full = substr(line, s, mlen)
        res = res substr(line, pos, RSTART - 1)
        sep = index(full, "](")
        label = substr(full, 1, sep + 1)
        url = substr(full, sep + 2, length(full) - sep - 2)
        # A link may carry an optional ` "title"` or ` 'title'` suffix
        # after the URL. Strip it before treating the remainder as the
        # path to rewrite, then reattach it unmodified afterward.
        title = ""
        ti = match(url, /[ \t]+["'\''][^"'\'']*["'\'']$/)
        if (ti > 0) {
          title = substr(url, ti)
          url = substr(url, 1, ti - 1)
        }
        if (is_relative_link(url)) {
          frag = ""; base = url
          fi = index(url, "#")
          if (fi > 0) { frag = substr(url, fi); base = substr(url, 1, fi - 1) }
          if (base != "") {
            resolved = normalize_path(dir "/" base)
            url = canonical "/" resolved frag
          }
        }
        res = res label url title ")"
        pos = s + mlen
      }
      res = res substr(line, pos)
      return res
    }
    function flush() {
      if (!seen) return
      if (FILENAME_PREV ~ /^\.agent\/rules\//) {
        emit("rules", "Source: " canonical "/" FILENAME_PREV "\n" body)
      } else {
        h = hook; if (h == "") h = "(no hook)"
        emit("routes", "- " title " | " h " | READ: " canonical "/" FILENAME_PREV)
      }
    }
    FNR == 1 {
      flush(); FILENAME_PREV = FILENAME; seen = 1; title = FILENAME; hook = ""; body = ""; titlefound = 0
      srcdir = FILENAME_PREV
      sub(/\/[^\/]*$/, "", srcdir)
    }
    {
      if (!titlefound && /^# /) { title = substr($0, 3); titlefound = 1 }
      if (hook == "" && match($0, /Read when:[ \t]*/)) {
        h = substr($0, RSTART + RLENGTH)
        sub(/-->[ \t]*$/, "", h)
        sub(/[ \t]+$/, "", h)
        hook = h
      }
      if (FILENAME ~ /^\.agent\/rules\//) {
        line = $0
        if (index(line, "](") > 0) line = rewrite_links(line, srcdir)
        body = body line "\n"
      }
    }
    END { flush() }
  ' "$@"
}

# --- resolve the current fingerprint and try a cache hit first ----------
fingerprint=$(snapshot) || fallback 'cannot fingerprint canonical source paths and bytes'

if valid_hit "$fingerprint"; then
  if [ "$op" = check ]; then
    printf 'FRESH\n'
    printf 'FRESH\n' >&2
    exit 0
  fi
  printf 'HIT\n' >&2
  printf '%s\n' "$HIT_ENTRY"
  exit 0
fi

if [ "$op" = check ]; then
  printf 'STALE\n'
  printf 'STALE\n' >&2
  exit 1
fi

# --- ensure: render, recheck sources, publish -----------------------------
mkdir -p "$cache"

prev_gen=''
if [ -f "$entry" ] && [ ! -L "$entry" ]; then
  prev_contents=$(cat "$entry" 2>/dev/null || true)
  prev_gen=${prev_contents#*$'\n'}; prev_gen=${prev_gen%%$'\n'*}
  case "$prev_gen" in gen.*) ;; *) prev_gen='' ;; esac
fi

attempt=1
while :; do
  pre_fp=$(snapshot) || fallback 'cannot fingerprint canonical source paths and bytes'
  gen=$(mktemp -d "$cache/gen.XXXXXXXX")
  files=()
  while IFS= read -r file; do files[${#files[@]}]=$file; done < <(paths "$root")
  [ "${#files[@]}" -gt 0 ] || fallback 'no source records under .agent/rules/ or .agent/docs/'
  render "$gen" "${files[@]}" || fallback 'render failed or a record exceeds the page budget'
  [ -n "$(find "$gen" -type f -name '*.md' -print -quit 2>/dev/null)" ] || fallback 'render produced no pages'
  [ "${INDEX_FAIL_AT:-}" != after-render ] || fallback 'injected failure after render'
  post_fp=$(snapshot) || fallback 'source recheck failed'
  [ "$post_fp" = "$pre_fp" ] && break
  rm -rf "$gen"; gen=''
  attempt=$((attempt + 1))
  [ "$attempt" -le "$MAX_BUILD_ATTEMPTS" ] \
    || fallback "sources changed on every attempt; exhausted $MAX_BUILD_ATTEMPTS render attempts"
done
fingerprint="$post_fp"

entry_tmp=$(mktemp "$cache/.entry.XXXXXXXX")
expected_entry "$fingerprint" "$gen" "$gen" >"$entry_tmp"
entry_bytes=$(wc -c <"$entry_tmp")
[ "$entry_bytes" -le "$budget" ] || fallback 'entry exceeds page budget'

# Prepared before either rename below, so a failure here (an unreadable
# record, a full disk) falls back through the same ERR trap with neither
# the entry nor the aggregate touched, same as any other failed ensure.
agg_tmp=''
if learned_dir_active "$root"; then
  agg_want=$(learned_aggregate_content "$root")
  agg_have=''
  if [ -f "$learned_agg" ] && [ ! -L "$learned_agg" ]; then
    agg_have=$(cat "$learned_agg" 2>/dev/null || true)
  fi
  if [ "$agg_want" != "$agg_have" ]; then
    [ ! -d "$learned_agg" ] || fallback 'learned aggregate path is a directory'
    agg_tmp=$(mktemp "$root/.agent/rules/.learned.XXXXXXXX")
    printf '%s\n' "$agg_want" >"$agg_tmp"
  fi
fi

[ "${INDEX_FAIL_AT:-}" != before-publish ] || fallback 'injected failure before publication'

# Immutable generations avoid mixed reads: this generation is never
# mutated again, and readers who already opened a prior entry keep a
# generation that publication below does not touch. keep is set only
# once the rename actually lands — a failed mv leaves keep=0, so the ERR
# trap's cleanup() reclaims this now-orphaned generation instead of
# leaking it.
mv -f "$entry_tmp" "$entry" && keep=1
entry_tmp=''
if [ -n "$agg_tmp" ]; then
  mv -f "$agg_tmp" "$learned_agg"
  agg_tmp=''
fi
new_gen="$gen"
gen=''

# Bounded cleanup: reclaim generations that are neither the one just
# published nor the one it replaced, and only once they are old enough
# that no build racing this one could still be relying on them (see
# CLEANUP_AGE_SECONDS above). The two most recent generations are always
# exempt regardless of age. On top of that, current.md's generation line
# is re-read immediately before each removal — not just trusted from the
# publish above — so a generation some other writer has since published
# over current.md is never removed here even if it is neither new_gen nor
# prev_gen and has aged past the bound.
now=$(date +%s)
for d in "$cache"/gen.*; do
  [ -d "$d" ] || continue
  base=${d##*/}
  [ "$base" = "${new_gen##*/}" ] && continue
  [ "$base" = "$prev_gen" ] && continue
  dm=$(mtime_epoch "$d") || continue
  age=$((now - dm))
  [ "$age" -ge "$CLEANUP_AGE_SECONDS" ] || continue
  live_gen=''
  if [ -f "$entry" ] && [ ! -L "$entry" ]; then
    live_gen=$(sed -n 2p "$entry" 2>/dev/null || true)
  fi
  [ "$base" = "$live_gen" ] && continue
  rm -rf "$d"
done

printf 'BUILT\n' >&2
printf '%s\n' "$entry"
