#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

schema_version=1
usage() {
  cat <<'EOF'
Usage:
  index.sh ensure [--root <path>] [--budget <bytes>]
  index.sh check  [--root <path>] [--budget <bytes>]
  index.sh --help
  index.sh --version

root defaults to . — the cache lives at <root>/.agent/indexes/.
budget defaults to 30000 and bounds each generated page and the entry
file, in bytes (256..1000000).
EOF
}

self_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
self="$self_dir/${BASH_SOURCE[0]##*/}"

CLEANUP_AGE_SECONDS=${INDEX_CLEANUP_AGE_SECONDS:-300}
MAX_BUILD_ATTEMPTS=5

case "${1:-}" in
--help | -h) usage; exit 0 ;;
--version) printf 'index.sh schema %s\n' "$schema_version"; exit 0 ;;
esac

op="${1:-}"
case "$op" in
ensure | check) shift ;;
*) usage >&2; exit 2 ;;
esac

root=$PWD
budget=30000
while [ "$#" -gt 0 ]; do
  case "$1" in
  --root | --budget)
    [ "$#" -ge 2 ] || { usage >&2; exit 2; }
    case "$1" in --root) root=$2 ;; --budget) budget=$2 ;; esac
    shift 2 ;;
  --help | -h) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
  esac
done
case "$budget" in '' | *[!0-9]*) usage >&2; exit 2 ;; esac
[ "$budget" -ge 256 ] && [ "$budget" -le 1000000 ] || { usage >&2; exit 2; }
[ -d "$root" ] || { usage >&2; exit 2; }
root=$(cd "$root" && pwd -P)
case "$root" in *\\* | *$'\n'* | *$'\r'* | *$'\t'*)
  printf 'index.sh: unsupported project path\n' >&2; exit 2 ;;
esac
[ -d "$root/.agent" ] || {
  printf 'index.sh: no %s/.agent directory — not a dot-agent node\n' "$root" >&2
  exit 2
}
cd "$root"
cache="$root/.agent/indexes"
entry="$cache/current.md"
learned_agg="$root/.agent/rules/learned.md"

learned_header=$(cat <<'HEADER_EOF'
# Learned rules

Binding rules distilled from operator corrections and failed verifications on this project, after the canonical-source check in `contract.md`. A correction that exposes a defect in the contract, docs, code, or tooling is fixed there and produces no compensating rule. Merging and compressing entries is allowed. Drop a rule when its failure mode becomes mechanically enforced. Behavioral rules stay here. Area gotchas go to the matching `.agent/docs/` file under `## Gotchas`. Authoring and curation rules: `contract.md`, Self-learning.

<!-- Format: - [YYYY-MM-DD] <imperative rule>. Trigger: <cause, optional>. -->
<!-- Generated by index.sh from rules/learned/*.md — hand edits here are lost on the next ensure. -->
HEADER_EOF
)

gen=''
entry_tmp=''
agg_tmp=''
keep=0
cleanup() {
  [ -z "$entry_tmp" ] || rm -f "$entry_tmp"
  [ -z "$agg_tmp" ] || rm -f "$agg_tmp"
  if [ -n "$gen" ] && [ "$keep" -eq 0 ]; then rm -rf "$gen"; fi
}
fallback() {
  printf 'ERROR: %s\n' "$*" >&2
  printf 'FALLBACK: read canonical Markdown under %s/.agent/rules/ and %s/.agent/docs/\n' "$root" "$root" >&2
  exit 1
}
trap cleanup EXIT
trap 'fallback "refresh failed at line $LINENO"' ERR
trap 'exit 130' INT
trap 'exit 143' TERM

[ ! -L "$cache" ] || fallback 'cache path is a symlink'
[ ! -d "$entry" ] || fallback 'entry path is a directory'

generator=$(git hash-object --no-filters -- "$self")

learned_dir_active() {
  lda_dir="$1/.agent/rules/learned"
  [ -d "$lda_dir" ] && [ ! -L "$lda_dir" ] || return 1
  [ -n "$(find "$lda_dir" -type f -name '*.md' -print -quit 2>/dev/null)" ]
}

learned_aggregate_content() {
  la_root="$1"
  printf '%s\n\n' "$learned_header"
  find "$la_root/.agent/rules/learned" -type f -name '*.md' | sort \
    | while IFS= read -r la_file; do
        cat "$la_file"
        [ "$(tail -c1 "$la_file" 2>/dev/null | wc -l | tr -d '[:space:]')" = 1 ] || printf '\n'
      done
}

paths() {
  proot="$1"
  ( [ -d "$proot/.agent/rules" ] && find "$proot/.agent/rules" -type l -print
    [ -d "$proot/.agent/docs" ] && find "$proot/.agent/docs" -type l -print
    true ) 2>/dev/null \
    | awk 'END { if (NR) exit 1 }' || return 1
  p_learned_active=0
  if learned_dir_active "$proot"; then p_learned_active=1; fi
  ( [ -d "$proot/.agent/rules" ] && find "$proot/.agent/rules" -type f -name '*.md' -print0
    [ -d "$proot/.agent/docs" ] && find "$proot/.agent/docs" -type f -name '*.md' -print0
    true ) \
    | while IFS= read -r -d '' file; do
        rel=${file#"$proot"/}
        case "$rel" in *[!a-zA-Z0-9_./-]*) exit 1 ;; esac
        if [ "$p_learned_active" -eq 1 ] && [ "$rel" = .agent/rules/learned.md ]; then
          continue
        fi
        if [ "$rel" = .agent/rules/quality-bar.md ]; then
          continue
        fi
        case "$rel" in */references/*) continue ;; esac
        printf '%s\n' "$rel"
      done | sort
}

absolute_paths() {
  aproot="$1"
  while IFS= read -r file; do printf '%s/%s\n' "$aproot" "$file"; done
}

snapshot() {
  sn_list=$(paths "$root") || return 1
  [ -n "$sn_list" ] || return 1
  sn_hashes=$(printf '%s\n' "$sn_list" | absolute_paths "$root" | git hash-object --no-filters --stdin-paths) || return 1
  printf '%s\n%s\n%s\n%s\n' "$schema_version/$budget/$generator" "$root" "$sn_list" "$sn_hashes" | git hash-object --stdin
}

tree_digest() {
  td_dir="$1"
  [ -d "$td_dir" ] && [ ! -L "$td_dir" ] || return 1
  td_list=$(cd "$td_dir" && find . -type f -name '*.md' | sed 's|^\./||' | sort) || return 1
  [ -n "$td_list" ] || return 1
  td_hashes=$(cd "$td_dir" && printf '%s\n' "$td_list" | absolute_paths "$td_dir" | git hash-object --no-filters --stdin-paths) || return 1
  printf '%s\n%s\n' "$td_list" "$td_hashes" | git hash-object --stdin
}

mtime_epoch() {
  stat -c '%Y' "$1" 2>/dev/null || stat -f '%m' "$1"
}

expected_entry() {
  ee_fp="$1" ee_gen="$2" ee_dir="$3"
  {
    printf '%s\n%s\n%s\n\n' "$ee_fp" "${ee_gen##*/}" "$(tree_digest "$ee_dir")"
    ( cd "$ee_dir" && find . -type f -name '*.md' | sed 's|^\./||' | sort ) \
      | while IFS= read -r pg; do printf 'READ: %s/%s\n' "$ee_dir" "$pg"; done
  }
}

HIT_ENTRY=''
valid_hit() {
  vh_fp="$1"
  [ -f "$entry" ] && [ ! -L "$entry" ] || return 1
  vh_contents=$(cat "$entry") || return 1
  vh_old_fp=${vh_contents%%$'\n'*}; vh_rest=${vh_contents#*$'\n'}
  vh_old_gen=${vh_rest%%$'\n'*}
  case "$vh_old_gen" in
  gen.*) case "$vh_old_gen" in *[!a-zA-Z0-9.]* | *..*) return 1 ;; esac ;;
  *) return 1 ;;
  esac
  [ "$vh_old_fp" = "$vh_fp" ] || return 1
  vh_dir="$cache/$vh_old_gen"
  [ -d "$vh_dir" ] && [ ! -L "$vh_dir" ] || return 1
  vh_expected=$(expected_entry "$vh_fp" "$vh_old_gen" "$vh_dir") || return 1
  [ "$vh_contents" = "$vh_expected" ] || return 1
  HIT_ENTRY="$entry"
  return 0
}

render() {
  rd_gen="$1"
  shift
  awk -v out="$rd_gen" -v canonical="$root" -v cap="$budget" '
    function emit(kind, text,    n,path) {
      n = length(text) + 1
      if (n > cap) { print "record exceeds page budget: " FILENAME_PREV > "/dev/stderr"; exit 4 }
      if (!page[kind] || size[kind] + n > cap) { page[kind]++; size[kind] = 0 }
      path = out "/" kind "-" page[kind] ".md"
      print text > path
      size[kind] += n
    }
    function is_relative_link(url) {
      if (url == "") return 0
      if (url ~ /^[A-Za-z][A-Za-z0-9+.-]*:/) return 0
      if (url ~ /^\//) return 0
      if (url ~ /^#/) return 0
      return 1
    }
    function normalize_path(path,    n, parts, i, seg, outn, joined) {
      n = split(path, parts, "/")
      outn = 0
      for (i = 1; i <= n; i++) {
        seg = parts[i]
        if (seg == "" || seg == ".") continue
        if (seg == "..") { if (outn > 0) outn--; continue }
        outn++
        parts[outn] = seg
      }
      joined = ""
      for (i = 1; i <= outn; i++) joined = joined (i > 1 ? "/" : "") parts[i]
      return joined
    }
    function rewrite_links(line, dir,    res, pos, s, mlen, full, sep, label, url, frag, base, resolved, fi, title, ti) {
      res = ""
      pos = 1
      while (match(substr(line, pos), /\[[^]]*\]\([^)]*\)/)) {
        s = pos + RSTART - 1
        mlen = RLENGTH
        full = substr(line, s, mlen)
        res = res substr(line, pos, RSTART - 1)
        sep = index(full, "](")
        label = substr(full, 1, sep + 1)
        url = substr(full, sep + 2, length(full) - sep - 2)
        title = ""
        ti = match(url, /[ \t]+["'\''][^"'\'']*["'\'']$/)
        if (ti > 0) {
          title = substr(url, ti)
          url = substr(url, 1, ti - 1)
        }
        if (is_relative_link(url)) {
          frag = ""; base = url
          fi = index(url, "#")
          if (fi > 0) { frag = substr(url, fi); base = substr(url, 1, fi - 1) }
          if (base != "") {
            resolved = normalize_path(dir "/" base)
            url = canonical "/" resolved frag
          }
        }
        res = res label url title ")"
        pos = s + mlen
      }
      res = res substr(line, pos)
      return res
    }
    function flush() {
      if (!seen) return
      if (FILENAME_PREV ~ /^\.agent\/rules\//) {
        emit("rules", "Source: " canonical "/" FILENAME_PREV "\n" body)
      } else {
        h = hook; if (h == "") h = "(no hook)"
        emit("routes", "- " title " | " h " | READ: " canonical "/" FILENAME_PREV)
      }
    }
    FNR == 1 {
      flush(); FILENAME_PREV = FILENAME; seen = 1; title = FILENAME; hook = ""; body = ""; titlefound = 0
      srcdir = FILENAME_PREV
      sub(/\/[^\/]*$/, "", srcdir)
    }
    {
      if (!titlefound && /^# /) { title = substr($0, 3); titlefound = 1 }
      if (hook == "" && match($0, /Read when:[ \t]*/)) {
        h = substr($0, RSTART + RLENGTH)
        sub(/-->[ \t]*$/, "", h)
        sub(/[ \t]+$/, "", h)
        hook = h
      }
      if (FILENAME ~ /^\.agent\/rules\//) {
        line = $0
        if (index(line, "](") > 0) line = rewrite_links(line, srcdir)
        body = body line "\n"
      }
    }
    END { flush() }
  ' "$@"
}

fingerprint=$(snapshot) || fallback 'cannot fingerprint canonical source paths and bytes'

if valid_hit "$fingerprint"; then
  if [ "$op" = check ]; then
    printf 'FRESH\n'
    printf 'FRESH\n' >&2
    exit 0
  fi
  printf 'HIT\n' >&2
  printf '%s\n' "$HIT_ENTRY"
  exit 0
fi

if [ "$op" = check ]; then
  printf 'STALE\n'
  printf 'STALE\n' >&2
  exit 1
fi

mkdir -p "$cache"

prev_gen=''
if [ -f "$entry" ] && [ ! -L "$entry" ]; then
  prev_contents=$(cat "$entry" 2>/dev/null || true)
  prev_gen=${prev_contents#*$'\n'}; prev_gen=${prev_gen%%$'\n'*}
  case "$prev_gen" in gen.*) ;; *) prev_gen='' ;; esac
fi

attempt=1
while :; do
  pre_fp=$(snapshot) || fallback 'cannot fingerprint canonical source paths and bytes'
  gen=$(mktemp -d "$cache/gen.XXXXXXXX")
  files=()
  while IFS= read -r file; do files[${#files[@]}]=$file; done < <(paths "$root")
  [ "${#files[@]}" -gt 0 ] || fallback 'no source records under .agent/rules/ or .agent/docs/'
  render "$gen" "${files[@]}" || fallback 'render failed or a record exceeds the page budget'
  [ -n "$(find "$gen" -type f -name '*.md' -print -quit 2>/dev/null)" ] || fallback 'render produced no pages'
  [ "${INDEX_FAIL_AT:-}" != after-render ] || fallback 'injected failure after render'
  post_fp=$(snapshot) || fallback 'source recheck failed'
  [ "$post_fp" = "$pre_fp" ] && break
  rm -rf "$gen"; gen=''
  attempt=$((attempt + 1))
  [ "$attempt" -le "$MAX_BUILD_ATTEMPTS" ] \
    || fallback "sources changed on every attempt; exhausted $MAX_BUILD_ATTEMPTS render attempts"
done
fingerprint="$post_fp"

entry_tmp=$(mktemp "$cache/.entry.XXXXXXXX")
expected_entry "$fingerprint" "$gen" "$gen" >"$entry_tmp"
entry_bytes=$(wc -c <"$entry_tmp")
[ "$entry_bytes" -le "$budget" ] || fallback 'entry exceeds page budget'

agg_tmp=''
if learned_dir_active "$root"; then
  agg_want=$(learned_aggregate_content "$root")
  agg_have=''
  if [ -f "$learned_agg" ] && [ ! -L "$learned_agg" ]; then
    agg_have=$(cat "$learned_agg" 2>/dev/null || true)
  fi
  if [ "$agg_want" != "$agg_have" ]; then
    [ ! -d "$learned_agg" ] || fallback 'learned aggregate path is a directory'
    agg_tmp=$(mktemp "$root/.agent/rules/.learned.XXXXXXXX")
    printf '%s\n' "$agg_want" >"$agg_tmp"
  fi
fi

[ "${INDEX_FAIL_AT:-}" != before-publish ] || fallback 'injected failure before publication'

mv -f "$entry_tmp" "$entry" && keep=1
entry_tmp=''
if [ -n "$agg_tmp" ]; then
  mv -f "$agg_tmp" "$learned_agg"
  agg_tmp=''
fi
new_gen="$gen"
gen=''

now=$(date +%s)
for d in "$cache"/gen.*; do
  [ -d "$d" ] || continue
  base=${d##*/}
  [ "$base" = "${new_gen##*/}" ] && continue
  [ "$base" = "$prev_gen" ] && continue
  dm=$(mtime_epoch "$d") || continue
  age=$((now - dm))
  [ "$age" -ge "$CLEANUP_AGE_SECONDS" ] || continue
  live_gen=''
  if [ -f "$entry" ] && [ ! -L "$entry" ]; then
    live_gen=$(sed -n 2p "$entry" 2>/dev/null || true)
  fi
  [ "$base" = "$live_gen" ] && continue
  rm -rf "$d"
done

printf 'BUILT\n' >&2
printf '%s\n' "$entry"
